### ISSUE TITLE
Gezielt Munition an Fahrzeugen editieren

### ISSUE THREAD

**Issue by TBMakuro** [TacticalBaconDevs/TBMod_Builder#3]
Eine Möglichkeit bei z.B. Panzern alle Shells zu entfernen, das MG aber voll zu lassen wäre klasse. Gelegentlich würde ich gern Panzer als Athmosphären Objekte setzen, habe aber jedes mal die Befürchtung das eine einzelne HE Shell ganze Trupps auslöscht.

**Comment by shukari** [comment]
https://github.com/TacticalBaconDevs/TBMod/issues/211
